FROM casualjim/scratch

# extract executable to root
ADD ./caddy.tar.gz /
ADD Caddyfile /etc/caddy/Caddyfile

VOLUME /etc/caddy
VOLUME /var/www
VOLUME /var/run/caddy

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["/caddy", "-agree=true", "-conf=/etc/caddy/Caddyfile"]
